from setuptools import setup

setup(
    name="blaze",
    version="0.1.0",
    packages=['blaze', 'blaze.ai', 'blaze.data', 'blaze.utils', 'blaze.scraping'],
    install_requires=[
        'anthropic>=0.20.0',
        'backoff>=2.2.1',
        'beautifulsoup4>=4.12.2',
        'feedparser==6.0.10',
        'joblib>=1.2.0',
        'listparser==0.19',
        'markdown==3.4.3',
        'numpy>=1.25.1',
        'openai>=1.6.1',
        'pandas>=2.2.2',
        'pinecone-client==4.0.0',
        'psycopg2-binary==2.9.9',
        'pydantic>=2.6.1',
        'python_dateutil>=2.8.2',
        'pytz==2023.3',
        'requests>=2.31.0',
        'scikit-learn==1.3.0',
        'selenium==4.11.2',
        'SQLAlchemy==2.0.24',
        'tiktoken==0.4.0',
        'tldextract==3.4.1',
        'user-agents==2.2.0',
        'voyageai==0.2.3',
        'weasyprint==60.2',
        'webdriver-manager==3.8.6'
    ],
    include_package_data=False,
)